spring.application.name=order-service
#SQL
spring.datasource.url=jdbc:mysql://localhost:3306/order_service

spring.datasource.username=root
spring.datasource.password=ArjunSingh1204
spring.jpa.hibernate.ddl.auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
server.port = 8081